### ISSUE TITLE
Pilot: Rasmus - Intro formulation

### ISSUE THREAD

**Issue by munterkalmsteiner** [DeepikaBadampudi/qmethod#8]
This sentence feel strange with the comma (on page 1):
"In order to do that we would, like to know your opinion on the topics that you as a code reviewer and/or contributor perceive to be important. The results of the study will be presented in a scientific publication."

Make it should be like:
"In order to do that we would like to know your opinion on the topics that you as a code reviewer and/or contributor perceive to be important. The results of the study will be presented in a scientific publication."

**Comment by rbritto82** [comment]
@munterkalmsteiner and @DeepikaBadampudi,  I suggest you rewrite the introduction as the following text:

 We are inviting you to participate in a survey, which is part of a research study conducted by Deepika Badampudi and Michael Unterkalmsteiner (Blekinge Institute of Technology, Sweden) and Ricardo Britto (Ericsson and Blekinge Institute of Technology, Sweden).

Before you take part in this survey, you must understand all of the associated details. Please read the following information carefully. If you have any questions or if you need more information, please contact any of the researchers mentioned above (see the contact information below).

The purpose of the research study is to transfer Modern Code Review Research to practice. To do so, we want to know your opinion on the topics related to Modern Code reviews that you, as a code reviewer or contributor, perceive to be necessary. We will present the results in a scientific publication. We estimate it takes about 25 minutes to answer the survey.

Your participation is essential to make it possible to transfer existing research to practice, which can support your daily work as a developer/code reviewer. As an additional benefit for you, we will share summaries of research papers that relate to your code review interests.

This study is anonymous. We will not retain your identity; i.e., we will only publish aggregated results, and the risk of disclosing your personal information is minimal.

Your participation in this study is voluntary. You are free to withdraw at any time in the research and without giving a reason.

**Comment by munterkalmsteiner** [comment]
Fixed in 5af0a5a43534aee6e96744168ca692758355d657
